### ISSUE TITLE
SIMPLE indexes are not working

### ISSUE THREAD

**Issue by gowhari** [josiahcarlson/rom#97] opened 2016-07-14 05:56 UTC
Am I using it wrong or it's a bug?

```python
import rom

class Person(rom.Model):
    fname = rom.String(required=True, index=True, keygen=rom.IDENTITY)
    lname = rom.String(required=True, index=True, keygen=rom.SIMPLE)

p = Person(fname='Sherlock', lname='Holmes')
p.save()

print Person.query.filter(fname='Sherlock').all()
# [<__main__.Person object at 0x7f22d8384150>]
print Person.query.filter(lname='Holmes').all()
# []
```

redis: 3.0.6
rom: 0.37.1

**Comment by josiahcarlson** [comment] 2016-07-15 05:05
There are 3 types of string indexes that rom currently supports:
1. SIMPLE/SIMPLE_CI - sorting only with `query.order_by('x')` - https://pythonhosted.org/rom/rom.html#rom.util.SIMPLE
2. IDENTITY/IDENTITY_CI - equality only with `query.filter(x=...)` - https://pythonhosted.org/rom/rom.html#rom.util.IDENTITY
3: FULL_TEXT - bag of words inverted index for query.filter(x=...)` - https://pythonhosted.org/rom/rom.html#rom.util.FULL_TEXT

To each of those 3 index types, you can further add a prefix/suffix index, whose semantics are as follows (prefix offers `query.startswith(pfix)` and `.query.like('stuff?*')`, suffix offers `query.endswith(sfix)`):
1. SIMPLE/SIMPLE_CI/IDENTITY/IDENTITY_CI - prefix/suffix the whole string case sensitive or insensitive
2. FULL_TEXT - prefix/suffix on individual words parsed out of the full text

Given your description, it would seem that you actually want `rom.IDENTITY` or `rom.FULL_TEXT` where you are currently using `rom.SIMPLE`, at least the way `rom.SIMPLE` is *specified* and built. If you actually need all of the variations of the index on a single column, you could duplicate the column data and have different indexes for the different columns, querying each one explicitly.

Or if you don't like to duplicate data, you can actually have additional columns with no data, but which generate indexes for other columns. This is actually supported right now as the `keygen2` argument available to most column types, documented: https://pythonhosted.org/rom/rom.html#rom.Column

Closing because everything is working as intended.

**Closed by josiahcarlson** 2016-07-15 05:05 UTC

**Comment by gowhari** [comment] 2016-07-15 12:12
Thank you very much for your response. I think **sorting only** can be a good phrase under SIMPLE docs, that prevents someone like me to steal your time.

**Comment by josiahcarlson** [comment] 2016-09-25 22:59
I have updated the docs to include the clearer specifications on each of the different index types: https://pythonhosted.org/rom/rom.html#rom.Column
