### ISSUE TITLE
Strange session issue with RQ?

### ISSUE THREAD

**Issue by jmmills** [josiahcarlson/rom#68] opened 2015-07-24 23:41 UTC
Please consider this gist: https://gist.github.com/jmmills/69c29463e5b61f72c80e
Strangely objects are lost out of the session when passed into a job queue like RQ despite being executed inside the same process. 
I fear I'm not yet experienced enough with Python to sort this out.

**Comment by josiahcarlson** [comment] 2015-07-25 06:02
RQ does not execute jobs inside the same process.

1. The `worker.work(burst=True)` definition: https://github.com/nvie/rq/blob/master/rq/worker.py#L391
2. The actual call to get work done: https://github.com/nvie/rq/blob/master/rq/worker.py#L431
3. Which leads to: https://github.com/nvie/rq/blob/master/rq/worker.py#L488-L514

Notice the `os.fork()` just after the docstring? Yeah, not the same process.

Either way, rom wasn't designed for entities to be passed into any remote job queues - which is what RQ is. Even if the worker were running in the same process, rom doesn't do serialization/deserialization of entities. And if RQ didn't complain when you dropped your just-created object in the queue*, then RQ is doing the wrong things to pass data around.

If you want to pass a rom entity through RQ (or any other task queue system), and you know that it is for a specific model, you should do what I do: put the primary key in the queue (which defaults to the `id` attribute when you don't explicitly include a `PrimaryKey()` attribute), then use `Model.get(primary_key)` in the job.

* I didn't install RQ, nor did I run the code you provided. Everything that I know about RQ I learned from reading the source code for RQ just now.

Closing this because it is not a bug with rom.

**Closed by josiahcarlson** 2015-07-25 06:02 UTC

**Comment by jmmills** [comment] 2015-07-25 06:11
Okay, I will attempt to just do the fetching with ```Model.get```. 
However, the example code given does not utilize ```os.fork```.

**Comment by josiahcarlson** [comment] 2015-07-25 06:37
Ahh, `SimpleWorker` vs `Worker`, my mistake.

In any case, the problem is that rom objects aren't built for serialization in/out of anything, so you'll have to pass the id or something else that can be serialized by RQ.

**Comment by jmmills** [comment] 2015-07-25 06:53
Thanks for the help!
