### ISSUE TITLE
Support Dynomite between Rom and Redis

### ISSUE THREAD

**Issue by natm** [josiahcarlson/rom#94] opened 2016-05-16 17:54 UTC
Please can Rom support Dynomite fronting Redis? [Dynomite](https://github.com/Netflix/dynomite) provides cross-datacentre replication and high availability.

I'm running Redis locally on 22122 and Dynomite on 8102 with this config:

```
dyn_o_mite:
  dyn_listen: 127.0.0.1:8101
  data_store: 0
  listen: 127.0.0.1:8102
  dyn_seed_provider: simple_provider
  servers:
  - 127.0.0.1:22122:1
  tokens: 437425602
```

Starting it up like:
```
dynomite -c dynomite_cfg.yml -m16384 -M100000
```

And then connecting using Rom in Python to Dynomite:

```python
#!/usr/bin/env python

import rom
import time

class User(rom.Model):
    email = rom.String(required=True, unique=True, suffix=True, keygen=rom.SIMPLE)
    salt = rom.String()
    hash = rom.String()
    created_at = rom.Float(default=time.time)

def main():
    rom.util.set_connection_settings(host="127.0.0.1", port=8102, db=0)

    # remove all users
    print "removing all users"
    for user in User.query.all():
        user.delete()

    # create one
    print "adding a user"
    newuser = User(email="test@test.com", salt="abc", hash="def")
    newuser.save()

    # retrieve it
    print "retrieving the user"
    user = User.get_by(email='test@test.com')
    print user.salt


if __name__ == "__main__":
    main()
```

Python error:
```
(venv)nat@natnf:~/stash/terrier/backend-lib (redis-orm-rom)$ python romtest.py
removing all users
Traceback (most recent call last):
  File "romtest.py", line 32, in <module>
    main()
  File "romtest.py", line 18, in main
    user.delete()
  File "/Users/nat/stash/terrier/backend-lib/venv/lib/python2.7/site-packages/rom/model.py", line 452, in delete
    _on_delete(self)
  File "/Users/nat/stash/terrier/backend-lib/venv/lib/python2.7/site-packages/rom/columns.py", line 111, in _on_delete
    self.delete(skip_on_delete_i_really_mean_it=SKIP_ON_DELETE)
  File "/Users/nat/stash/terrier/backend-lib/venv/lib/python2.7/site-packages/rom/model.py", line 455, in delete
    self._apply_changes(self._last, {}, delete=True)
  File "/Users/nat/stash/terrier/backend-lib/venv/lib/python2.7/site-packages/rom/model.py", line 402, in _apply_changes
    delete)
  File "/Users/nat/stash/terrier/backend-lib/venv/lib/python2.7/site-packages/rom/model.py", line 776, in redis_writer_lua
    result = _redis_writer_lua(conn, [], [namespace, id] + data)
  File "/Users/nat/stash/terrier/backend-lib/venv/lib/python2.7/site-packages/rom/util.py", line 731, in call
    'EVAL', script, len(keys), *(keys + args))
  File "/Users/nat/stash/terrier/backend-lib/venv/lib/python2.7/site-packages/redis/client.py", line 579, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/Users/nat/stash/terrier/backend-lib/venv/lib/python2.7/site-packages/redis/client.py", line 585, in parse_response
    response = connection.read_response()
  File "/Users/nat/stash/terrier/backend-lib/venv/lib/python2.7/site-packages/redis/connection.py", line 577, in read_response
    response = self._parser.read_response()
  File "/Users/nat/stash/terrier/backend-lib/venv/lib/python2.7/site-packages/redis/connection.py", line 238, in read_response
    response = self._buffer.readline()
  File "/Users/nat/stash/terrier/backend-lib/venv/lib/python2.7/site-packages/redis/connection.py", line 168, in readline
    self._read_from_socket()
  File "/Users/nat/stash/terrier/backend-lib/venv/lib/python2.7/site-packages/redis/connection.py", line 143, in _read_from_socket
    (e.args,))
redis.exceptions.ConnectionError: Error while reading from socket: ('Connection closed by server.',)
```

Dynomite (at verbose level 6):
```
[2016-05-16 18:52:09.795] proxy_accept:353 accepted CLIENT 10 on PROXY 8 from '127.0.0.1:56952'
[2016-05-16 18:52:09.795] redis_parse_req:1810 parsed bad req 6 res 1 type 125 state 17
00000000  2a 31 35 0d 0a 24 34 0d  0a 45 56 41 4c 0d 0a 24   |*15..$4..EVAL..$|
00000010  34 34 34 36 0d 0a 0a 6c  6f 63 61 6c 20 6e 61 6d   |4446...local nam|
00000020  65 73 70 61 63 65 20 3d  20 41 52 47 56 5b 31 5d   |espace = ARGV[1]|
00000030  0a 6c 6f 63 61 6c 20 69  64 20 3d 20 41 52 47 56   |.local id = ARGV|
00000040  5b 32 5d 0a 6c 6f 63 61  6c 20 72 6f 77 5f 6b 65   |[2].local row_ke|
00000050  79 20 3d 20 73 74 72 69  6e 67 2e 66 6f 72 6d 61   |y = string.forma|
00000060  74 28 27 25 73 3a 25 73  27 2c 20 6e 61 6d 65 73   |t('%s:%s', names|
00000070  70 61 63 65 2c 20 69 64  29 0a 6c 6f 63 61 6c 20   |pace, id).local |
00000080  69 73 5f 64 65 6c 65 74  65 20 3d 20 63 6a 73 6f   |is_delete = cjso|
00000090  6e 2e 64 65 63 6f 64 65  28 41 52 47 56 5b 31 31   |n.decode(ARGV[11|
000000a0  5d 29 0a 0a 2d 2d 20 5b  31 5d 20 73 74 72 69 6e   |])..-- [1] strin|
000000b0  67 2e 66 6f 72 6d 61 74  28 22 25 73 22 2c 20 64   |g.format("%s", d|
000000c0  29 20 77 69 6c 6c 20 74  72 75 6e 63 61 74 65 20   |) will truncate |
000000d0  64 20 74 6f 20 74 68 65  20 66 69 72 73 74 20 6e   |d to the first n|
000000e0  75 6c 6c 20 76 61 6c 75  65 2c 20 73 6f 20 77 65   |ull value, so we|
000000f0  0a 2d 2d 20 20 20 20 20  63 61 6e 27 74 20 72 65   |.--     can't re|
00000100  6c 79 20 6f 6e 20 73 74  72 69 6e 67 2e 66 6f 72   |ly on string.for|
00000110  6d 61 74 28 29 20 77 68  65 72 65 20 77 65 20 63   |mat() where we c|
00000120  61 6e 20 72 65 61 73 6f  6e 61 62 6c 79 20 65 78   |an reasonably ex|
00000130  70 65 63 74 20 6e 75 6c  6c 73 2e 0a 0a 69 66 20   |pect nulls...if |
00000140  6e 6f 74 20 69 73 5f 64  65 6c 65 74 65 20 74 68   |not is_delete th|
00000150  65 6e 0a 20 20 20 20 2d  2d 20 63 68 65 63 6b 20   |en.    -- check |
00000160  74 6f 20 6d 61 6b 65 20  73 75 72 65 20 77 65 20   |to make sure we |
00000170  64 6f 6e 27 74 20 68 61  76 65 20 61 20 64 61 74   |don't have a dat|
00000180  61 20 72 61 63 65 20 63  6f 6e 64 69 74 69 6f 6e   |a race condition|
00000190  0a 20 20 20 20 6c 6f 63  61 6c 20 75 70 64 61 74   |.    local updat|
000001a0  65 64 20 3d 20 7b 7d 0a  20 20 20 20 66 6f 72 20   |ed = {}.    for |
000001b0  69 2c 20 70 61 69 72 20  69 6e 20 69 70 61 69 72   |i, pair in ipair|
000001c0  73 28 63 6a 73 6f 6e 2e  64 65 63 6f 64 65 28 41   |s(cjson.decode(A|
000001d0  52 47 56 5b 31 32 5d 29  29 20 64 6f 0a 20 20 20   |RGV[12])) do.   |
000001e0  20 20 20 20 20 6c 6f 63  61 6c 20 6f 64 61 74 61   |     local odata|
000001f0  20 3d 20 72 65 64 69 73  2e 63 61 6c 6c 28 27 48   | = redis.call('H|
00000200  47 45 54 27 2c 20 72 6f  77 5f 6b 65 79 2c 20 70   |GET', row_key, p|
00000210  61 69 72 5b 31 5d 29 0a  20 20 20 20 20 20 20 20   |air[1]).        |
00000220  69 66 20 6f 64 61 74 61  20 7e 3d 20 70 61 69 72   |if odata ~= pair|
00000230  5b 32 5d 20 74 68 65 6e  0a 20 20 20 20 20 20 20   |[2] then.       |
00000240  20 20 20 20 20 74 61 62  6c 65 2e 69 6e 73 65 72   |     table.inser|
00000250  74 28 75 70 64 61 74 65  64 2c 20 70 61 69 72 5b   |t(updated, pair[|
00000260  31 5d 29 0a 20 20 20 20  20 20 20 20 65 6e 64 0a   |1]).        end.|
00000270  20 20 20 20 65 6e 64 0a  20 20 20 20 69 66 20 23   |    end.    if #|
00000280  75 70 64 61 74 65 64 20  3e 20 30 20 74 68 65 6e   |updated > 0 then|
00000290  0a 20 20 20 20 20 20 20  20 72 65 74 75 72 6e 20   |.        return |
000002a0  63 6a 73 6f 6e 2e 65 6e  63 6f 64 65 28 7b 72 61   |cjson.encode({ra|
000002b0  63 65 3d 75 70 64 61 74  65 64 7d 29 0a 20 20 20   |ce=updated}).   |
000002c0  20 65 6e 64 0a 65 6e 64  0a 0a 2d 2d 20 63 68 65   | end.end..-- che|
000002d0  63 6b 20 61 6e 64 20 75  70 64 61 74 65 20 75 6e   |ck and update un|
000002e0  69 71 75 65 20 63 6f 6c  75 6d 6e 20 63 6f 6e 73   |ique column cons|
000002f0  74 72 61 69 6e 74 73 0a  66 6f 72 20 69 2c 20 77   |traints.for i, w|
00000300  72 69 74 65 20 69 6e 20  69 70 61 69 72 73 28 7b   |rite in ipairs({|
00000310  66 61 6c 73 65 2c 20 74  72 75 65 7d 29 20 64 6f   |false, true}) do|
00000320  0a 20 20 20 20 66 6f 72  20 63 6f 6c 2c 20 76 61   |.    for col, va|
00000330  6c 75[2016-05-16 18:52:09.796] core_recv:270 recv on CLIENT 10 failed: Invalid argument
[2016-05-16 18:52:09.796] core_close_log:304 close CLIENT 10 '127.0.0.1:56952' on event 00FF eof 0 done 0 rb 4657 sb 0: Invalid argument
[2016-05-16 18:52:09.796] client_close:227 close c 10 discarding pending req 6 len 4657 type 125
```

Support for this would allow people to use Rom at a large scale, currently looks like the LUA produced by Rom is not being executed correctly.

Be great to see these components all working together!

**Comment by ipapapa** [comment] 2016-05-16 18:03
I think the root cause of the above issue is because Dynomite supports EVAL/EVALSHA with at least one key.

From: https://github.com/Netflix/dynomite/blob/dev/notes/redis.md
_EVAL and EVALSHA support is limited to scripts that take at least 1 key. If multiple keys are used, all keys must hash to the same server. You can ensure this by using the same hashtag for all keys. If you use more than 1 key, the proxy does no checking to verify that all keys hash to the same server, and the entire command is forwarded to the server that the first key hashes to_

For example:

`127.0.0.1:8102> eval "return redis.call('set','foo','bar')" 0
Error: Server closed the connection
127.0.0.1:8102> eval "return redis.call('set',KEYS[1],'bar')" 1 foo
OK
127.0.0.1:8102>`

**Comment by josiahcarlson** [comment] 2016-05-16 19:07
Reading Dynomite's limitations, it is clear that it is fundamentally incompatible with the basic design decisions around how rom was built. Adding support for Dynomite would require a complete rewrite of the indexing and search subsystem that rom uses.

If you'd like to inquire about my contracting rates for building a distributed search backend compatible with Dynomite (which may induce Redis Cluster compatibility as a bonus), email my personal address attached to my Github account.

Closing this issue as being way the hell out of scope of what rom was designed and built to do.

**Closed by josiahcarlson** 2016-05-16 19:07 UTC
