### ISSUE TITLE
filter is always returning 0 results, even when manually verifying that results are present in redis

### ISSUE THREAD

**Issue by Slater-Victoroff** [josiahcarlson/rom#114] opened 2017-09-17 22:53 UTC
Trying for a very simple search by exact string match, but always getting 0 results.

Model: 

```
class IMASentence(rom.Model):
	uuid = rom.String(required=True, unique=True)
	section = rom.String(required=True, index=True, keygen=FULL_TEXT)
```
After ingestion, seeing this object:
```
127.0.0.1:6379> hgetall IMASentence:135
 1) "uuid"
 2) "31f3254b-9b7e-4dea-a190-01bd900a37f8"
 3) "section"
 4) "Voting"
 5) "id"
 6) "135"

```
Then at query time:
```
examples = IMASentence.query.filter(section="Voting").all()
len(examples) == 0
```
Happens regardless of keygen function, and regardless of the specific section I'm looking for. I'm wondering if I did something strange here, but I'm trying to follow the docs as closely as possible and can't figure out if/where I've gone wrong.

**Comment by Slater-Victoroff** [comment] 2017-09-17 23:06
The following code works, which I think confirms this as a bug:
```
examples = [example for example in IMASentence.query.all() if example.section == "Voting"]
```

**Comment by josiahcarlson** [comment] 2017-09-19 18:48
I'm seeing this as well. I ... am not sure when this happened. Let me bisect this and find out...

**Comment by josiahcarlson** [comment] 2017-09-19 19:32
Okay, the issue isn't nearly as scary as it seems. It should have been fixed with https://github.com/josiahcarlson/rom/issues/95, but my fix there was incomplete. Long story short, I needed to lowercase more things in more places. I just pushed 0.40.1 to master and pypi that should fix this.

**Comment by josiahcarlson** [comment] 2017-09-19 19:34
Details of the fix can be found here: https://github.com/josiahcarlson/rom/commit/47a417f52bcc17fa3b478e4db8034e6698ea0aeb

**Closed by josiahcarlson** 2017-09-19 19:34 UTC

**Comment by Goury** [comment] 2021-01-11 03:24
@josiahcarlson 
It's broken again in 1.0.0 and 1.0.1
index is True, keygen is rom.SIMPLE or rom.FULL_TEXT

Why?

**Comment by josiahcarlson** [comment] 2021-01-11 23:04
I don't know what to tell you. Tests pass.
