### ISSUE TITLE
in colums.py on line 271th convert(value)  need a argment encoding 

### ISSUE THREAD

**Issue by summer1988** [josiahcarlson/rom#85] opened 2015-11-18 14:12 UTC
python3.5
this line should check the convert(may be a object bytes/str/int/float and others),
if the convert object is str or bytes, it should have a argument encoding for encode the value(may be str) object.

**Comment by josiahcarlson** [comment] 2015-11-19 05:59
Is this theoretical, or do you have an example where this is an issue? The only situation where this is known to be an issue is in the same cases where #84 comes up. Are you having the same problem as #84?

**Comment by josiahcarlson** [comment] 2015-11-19 07:24
The problem is related to #84, in as much as there are several problems with binary strings in rom, and I'm close to having a general solution for them.

**Comment by josiahcarlson** [comment] 2015-11-20 06:25
Released 0.35.0, which fixes this issue. Closing.

**Closed by josiahcarlson** 2015-11-20 06:25 UTC
