### ISSUE TITLE
Query with empty string filter returns no results

### ISSUE THREAD

**Issue by fnadav** [josiahcarlson/rom#135] opened 2019-03-24 15:54 UTC
redis==2.10.5
rom==0.42.4

Description:
```
I have the following data in the rom model:
[{name: 'hi', value: 'blurp'}, {name: 'naruto', value: ''}]

When performing a cls.query.filter().all() i get:
[{name: 'hi', value: 'blurp'}, {name: 'naruto', value: ''}]

When performing a cls.query.filter(value='blurp').all() i get:
[{name: 'hi', value: 'blurp'}]

But when performing a cls.query.filter(value='').all() i get:
[]    --> **no results!**
```

its always reproducible, but if more details are required let me know

Thanks and regards!

PS, this is my schema:
```
class _Tags(rom.Model):
    name = rom.String(required=True, index=True, keygen=rom.IDENTITY,
                      prefix=True, suffix=True)
    value = rom.String(required=True, index=True, keygen=rom.IDENTITY)
    unique_together = [('name', 'value')]
```

edits: made the text more readable

**Comment by josiahcarlson** [comment] 2019-04-24 04:58
Sorry I took so long to get back to you. I've been thinking about how to address the issue, as rom does some work to not let empty strings / None's make their way into the index - and thus queries would necessarily return nothing. That is the case since the first real commit of the code: https://github.com/josiahcarlson/rom/commit/abf9fbb17e7308de191f063ef9d5e7122f4a322a#diff-8bba68db04d2531eb254ffbed64fde3aR85

That said, aside from some existing bugs that are demonstrated by your example (which have been fixed in rom 0.42.5), you should be able to get what you want by specifying a custom keygen after update:

```
In [102]: import rom 
     ...: import redis 
     ...:  

In [105]: def allow_empty(val): 
     ...:     if isinstance(val, str): 
     ...:         val = val.encode('utf-8') 
     ...:     if val: 
     ...:         return rom.IDENTITY(val) 
     ...:     return [''] 
     ...:  
     ...: class _Tags(rom.Model): 
     ...:     name = rom.String(required=True, index=True, keygen=rom.IDENTITY, 
     ...:                       prefix=True, suffix=True) 
     ...:     value = rom.String(required=True, index=True, keygen=allow_empty) 
     ...:     unique_together = [('name', 'value')] 
     ...:                                                                                                               

In [106]: _Tags(name='naruto', value='burp').save()                                                                     
Out[106]: 3

In [107]: _Tags(name='sasuke', value='').save()                                                                         
Out[107]: 3

In [108]: print(_Tags.query.filter(value='burp').all()) 
     ...: print(_Tags.query.filter(value='').all())                                                                     
[<__main__._Tags object at 0x7febb0112438>]
[<__main__._Tags object at 0x7febb0126cc0>]
'''

**Comment by josiahcarlson** [comment] 2019-04-24 05:01
In order to get this data able to be queried, you need to re-index any data that is affected (probably most, considering the bugfix I just applied). To re-index and show the progress of the reindex, you can run: `rom.util.show_progress(rom.util.refresh_indices(_Tags))` .

**Closed** 2019-04-24 05:03 UTC
Labels: bug, fixed, question

**Comment by Goury** [comment] 2021-01-11 03:20
@josiahcarlson 
```
----> 1 rom.util.show_progress(rom.util.refresh_indices(Log))

venv/lib/python3.8/site-packages/rom/util.py in show_progress(job)
    870     last_print = 0
    871     last_line = 0
--> 872     for prog, total in chain(job, [(1, 1)]):
    873         # Only print a line when we start, finish, or every .1 seconds
    874         if (time.time() - last_print) > .1 or prog >= total:

venv/lib/python3.8/site-packages/rom/util.py in refresh_indices(model, block_size, scan)
    741         blocks = (list(range(i, i+block_size)) for i in range(1, max_id+1, block_size))
    742 
--> 743     for i, block in enumerate(blocks):
    744         # fetches entities, keeping a record in the session
    745         models = model.get(block)

venv/lib/python3.8/site-packages/rom/util.py in _get_row_ids(model, block_size)
    697     cursor = 0
    698     pfx = "%s:"%(model._namespace,)
--> 699     for cursor, chunk in model._connection.scan(cursor, pfx + "*", block_size):
    700         oc = []
    701         for v in chunk:

TypeError: cannot unpack non-iterable int object
```

Why?

**Comment by josiahcarlson** [comment] 2021-01-11 23:10
Looks like upstream redis-py changed. What version of redis-py are you using?

**Comment by josiahcarlson** [comment] 2021-01-11 23:10
Or no, I'm expecting the wrong type for scans.

**Comment by josiahcarlson** [comment] 2021-01-11 23:13
Or, actually this is caused by just a bad call / return type / expected. Not sure when it was ever like this, but I'll fix.
